### ISSUE TITLE
Google will force-replace Hangouts with Google Chat next year, are there plans to support it in Pidgin?

### ISSUE THREAD

**Issue by alexolog** [EionRobb/purple-hangouts#224] opened 2020-10-17 00:37 UTC
https://www.theverge.com/2020/10/15/21517929/google-hangouts-chat-messaging-free

**Comment by TerryRPatterson** [comment] 2020-10-26 12:30
This appears to be a duplicate of #191

**Comment by EionRobb** [comment] 2021-06-19 23:13
Dup of #191

**Closed by EionRobb** 2021-06-19 23:13 UTC
